plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/private/var/folders/6f/ksc63lh16t54hwx8bh_dc1yr0000gn/T/tmp.ntxc6DMiFe"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]